/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as CurrencyRouteImport } from './routes/currency'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDownloadRouteImport } from './routes/api/download'
import { Route as ApiCurrencyRouteImport } from './routes/api/currency'
import { Route as ApiConvertRouteImport } from './routes/api/convert'

const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyRoute = CurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurrencyRoute = ApiCurrencyRouteImport.update({
  id: '/api/currency',
  path: '/api/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConvertRoute = ApiConvertRouteImport.update({
  id: '/api/convert',
  path: '/api/convert',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/currency': typeof CurrencyRoute
  '/download': typeof DownloadRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/currency': typeof ApiCurrencyRoute
  '/api/download': typeof ApiDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/currency': typeof CurrencyRoute
  '/download': typeof DownloadRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/currency': typeof ApiCurrencyRoute
  '/api/download': typeof ApiDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/currency': typeof CurrencyRoute
  '/download': typeof DownloadRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/currency': typeof ApiCurrencyRoute
  '/api/download': typeof ApiDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/currency'
    | '/download'
    | '/api/convert'
    | '/api/currency'
    | '/api/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/currency'
    | '/download'
    | '/api/convert'
    | '/api/currency'
    | '/api/download'
  id:
    | '__root__'
    | '/'
    | '/currency'
    | '/download'
    | '/api/convert'
    | '/api/currency'
    | '/api/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CurrencyRoute: typeof CurrencyRoute
  DownloadRoute: typeof DownloadRoute
  ApiConvertRoute: typeof ApiConvertRoute
  ApiCurrencyRoute: typeof ApiCurrencyRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency': {
      id: '/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof CurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/currency': {
      id: '/api/currency'
      path: '/api/currency'
      fullPath: '/api/currency'
      preLoaderRoute: typeof ApiCurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/convert': {
      id: '/api/convert'
      path: '/api/convert'
      fullPath: '/api/convert'
      preLoaderRoute: typeof ApiConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CurrencyRoute: CurrencyRoute,
  DownloadRoute: DownloadRoute,
  ApiConvertRoute: ApiConvertRoute,
  ApiCurrencyRoute: ApiCurrencyRoute,
  ApiDownloadRoute: ApiDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
