/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as TokenizerRouteImport } from './routes/tokenizer'
import { Route as SpeedRouteImport } from './routes/speed'
import { Route as ScreenshotRouteImport } from './routes/screenshot'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as IpRouteImport } from './routes/ip'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as EncodeRouteImport } from './routes/encode'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DigRouteImport } from './routes/dig'
import { Route as CurrencyRouteImport } from './routes/currency'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PasteIndexRouteImport } from './routes/paste/index'
import { Route as PasteIdRouteImport } from './routes/paste/$id'
import { Route as ApiSpeedRouteImport } from './routes/api/speed'
import { Route as ApiScreenshotRouteImport } from './routes/api/screenshot'
import { Route as ApiPdfRouteImport } from './routes/api/pdf'
import { Route as ApiPasteRouteImport } from './routes/api/paste'
import { Route as ApiIpRouteImport } from './routes/api/ip'
import { Route as ApiDownloadRouteImport } from './routes/api/download'
import { Route as ApiDigRouteImport } from './routes/api/dig'
import { Route as ApiCurrencyRouteImport } from './routes/api/currency'
import { Route as ApiConvertRouteImport } from './routes/api/convert'
import { Route as ApiPasteIdRouteImport } from './routes/api/paste.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenizerRoute = TokenizerRouteImport.update({
  id: '/tokenizer',
  path: '/tokenizer',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedRoute = SpeedRouteImport.update({
  id: '/speed',
  path: '/speed',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotRoute = ScreenshotRouteImport.update({
  id: '/screenshot',
  path: '/screenshot',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const IpRoute = IpRouteImport.update({
  id: '/ip',
  path: '/ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const EncodeRoute = EncodeRouteImport.update({
  id: '/encode',
  path: '/encode',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DigRoute = DigRouteImport.update({
  id: '/dig',
  path: '/dig',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyRoute = CurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasteIndexRoute = PasteIndexRouteImport.update({
  id: '/paste/',
  path: '/paste/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasteIdRoute = PasteIdRouteImport.update({
  id: '/paste/$id',
  path: '/paste/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeedRoute = ApiSpeedRouteImport.update({
  id: '/api/speed',
  path: '/api/speed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenshotRoute = ApiScreenshotRouteImport.update({
  id: '/api/screenshot',
  path: '/api/screenshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfRoute = ApiPdfRouteImport.update({
  id: '/api/pdf',
  path: '/api/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasteRoute = ApiPasteRouteImport.update({
  id: '/api/paste',
  path: '/api/paste',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIpRoute = ApiIpRouteImport.update({
  id: '/api/ip',
  path: '/api/ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigRoute = ApiDigRouteImport.update({
  id: '/api/dig',
  path: '/api/dig',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurrencyRoute = ApiCurrencyRouteImport.update({
  id: '/api/currency',
  path: '/api/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConvertRoute = ApiConvertRouteImport.update({
  id: '/api/convert',
  path: '/api/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasteIdRoute = ApiPasteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPasteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/currency': typeof CurrencyRoute
  '/dig': typeof DigRoute
  '/download': typeof DownloadRoute
  '/encode': typeof EncodeRoute
  '/images': typeof ImagesRoute
  '/ip': typeof IpRoute
  '/pdf': typeof PdfRoute
  '/screenshot': typeof ScreenshotRoute
  '/speed': typeof SpeedRoute
  '/tokenizer': typeof TokenizerRoute
  '/video': typeof VideoRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/currency': typeof ApiCurrencyRoute
  '/api/dig': typeof ApiDigRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/ip': typeof ApiIpRoute
  '/api/paste': typeof ApiPasteRouteWithChildren
  '/api/pdf': typeof ApiPdfRoute
  '/api/screenshot': typeof ApiScreenshotRoute
  '/api/speed': typeof ApiSpeedRoute
  '/paste/$id': typeof PasteIdRoute
  '/paste/': typeof PasteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paste/$id': typeof ApiPasteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/currency': typeof CurrencyRoute
  '/dig': typeof DigRoute
  '/download': typeof DownloadRoute
  '/encode': typeof EncodeRoute
  '/images': typeof ImagesRoute
  '/ip': typeof IpRoute
  '/pdf': typeof PdfRoute
  '/screenshot': typeof ScreenshotRoute
  '/speed': typeof SpeedRoute
  '/tokenizer': typeof TokenizerRoute
  '/video': typeof VideoRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/currency': typeof ApiCurrencyRoute
  '/api/dig': typeof ApiDigRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/ip': typeof ApiIpRoute
  '/api/paste': typeof ApiPasteRouteWithChildren
  '/api/pdf': typeof ApiPdfRoute
  '/api/screenshot': typeof ApiScreenshotRoute
  '/api/speed': typeof ApiSpeedRoute
  '/paste/$id': typeof PasteIdRoute
  '/paste': typeof PasteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paste/$id': typeof ApiPasteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/currency': typeof CurrencyRoute
  '/dig': typeof DigRoute
  '/download': typeof DownloadRoute
  '/encode': typeof EncodeRoute
  '/images': typeof ImagesRoute
  '/ip': typeof IpRoute
  '/pdf': typeof PdfRoute
  '/screenshot': typeof ScreenshotRoute
  '/speed': typeof SpeedRoute
  '/tokenizer': typeof TokenizerRoute
  '/video': typeof VideoRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/currency': typeof ApiCurrencyRoute
  '/api/dig': typeof ApiDigRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/ip': typeof ApiIpRoute
  '/api/paste': typeof ApiPasteRouteWithChildren
  '/api/pdf': typeof ApiPdfRoute
  '/api/screenshot': typeof ApiScreenshotRoute
  '/api/speed': typeof ApiSpeedRoute
  '/paste/$id': typeof PasteIdRoute
  '/paste/': typeof PasteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paste/$id': typeof ApiPasteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio'
    | '/currency'
    | '/dig'
    | '/download'
    | '/encode'
    | '/images'
    | '/ip'
    | '/pdf'
    | '/screenshot'
    | '/speed'
    | '/tokenizer'
    | '/video'
    | '/api/convert'
    | '/api/currency'
    | '/api/dig'
    | '/api/download'
    | '/api/ip'
    | '/api/paste'
    | '/api/pdf'
    | '/api/screenshot'
    | '/api/speed'
    | '/paste/$id'
    | '/paste/'
    | '/api/auth/$'
    | '/api/paste/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio'
    | '/currency'
    | '/dig'
    | '/download'
    | '/encode'
    | '/images'
    | '/ip'
    | '/pdf'
    | '/screenshot'
    | '/speed'
    | '/tokenizer'
    | '/video'
    | '/api/convert'
    | '/api/currency'
    | '/api/dig'
    | '/api/download'
    | '/api/ip'
    | '/api/paste'
    | '/api/pdf'
    | '/api/screenshot'
    | '/api/speed'
    | '/paste/$id'
    | '/paste'
    | '/api/auth/$'
    | '/api/paste/$id'
  id:
    | '__root__'
    | '/'
    | '/audio'
    | '/currency'
    | '/dig'
    | '/download'
    | '/encode'
    | '/images'
    | '/ip'
    | '/pdf'
    | '/screenshot'
    | '/speed'
    | '/tokenizer'
    | '/video'
    | '/api/convert'
    | '/api/currency'
    | '/api/dig'
    | '/api/download'
    | '/api/ip'
    | '/api/paste'
    | '/api/pdf'
    | '/api/screenshot'
    | '/api/speed'
    | '/paste/$id'
    | '/paste/'
    | '/api/auth/$'
    | '/api/paste/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioRoute: typeof AudioRoute
  CurrencyRoute: typeof CurrencyRoute
  DigRoute: typeof DigRoute
  DownloadRoute: typeof DownloadRoute
  EncodeRoute: typeof EncodeRoute
  ImagesRoute: typeof ImagesRoute
  IpRoute: typeof IpRoute
  PdfRoute: typeof PdfRoute
  ScreenshotRoute: typeof ScreenshotRoute
  SpeedRoute: typeof SpeedRoute
  TokenizerRoute: typeof TokenizerRoute
  VideoRoute: typeof VideoRoute
  ApiConvertRoute: typeof ApiConvertRoute
  ApiCurrencyRoute: typeof ApiCurrencyRoute
  ApiDigRoute: typeof ApiDigRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  ApiIpRoute: typeof ApiIpRoute
  ApiPasteRoute: typeof ApiPasteRouteWithChildren
  ApiPdfRoute: typeof ApiPdfRoute
  ApiScreenshotRoute: typeof ApiScreenshotRoute
  ApiSpeedRoute: typeof ApiSpeedRoute
  PasteIdRoute: typeof PasteIdRoute
  PasteIndexRoute: typeof PasteIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokenizer': {
      id: '/tokenizer'
      path: '/tokenizer'
      fullPath: '/tokenizer'
      preLoaderRoute: typeof TokenizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speed': {
      id: '/speed'
      path: '/speed'
      fullPath: '/speed'
      preLoaderRoute: typeof SpeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshot': {
      id: '/screenshot'
      path: '/screenshot'
      fullPath: '/screenshot'
      preLoaderRoute: typeof ScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip': {
      id: '/ip'
      path: '/ip'
      fullPath: '/ip'
      preLoaderRoute: typeof IpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encode': {
      id: '/encode'
      path: '/encode'
      fullPath: '/encode'
      preLoaderRoute: typeof EncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dig': {
      id: '/dig'
      path: '/dig'
      fullPath: '/dig'
      preLoaderRoute: typeof DigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency': {
      id: '/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof CurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paste/': {
      id: '/paste/'
      path: '/paste'
      fullPath: '/paste/'
      preLoaderRoute: typeof PasteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paste/$id': {
      id: '/paste/$id'
      path: '/paste/$id'
      fullPath: '/paste/$id'
      preLoaderRoute: typeof PasteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speed': {
      id: '/api/speed'
      path: '/api/speed'
      fullPath: '/api/speed'
      preLoaderRoute: typeof ApiSpeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screenshot': {
      id: '/api/screenshot'
      path: '/api/screenshot'
      fullPath: '/api/screenshot'
      preLoaderRoute: typeof ApiScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf': {
      id: '/api/pdf'
      path: '/api/pdf'
      fullPath: '/api/pdf'
      preLoaderRoute: typeof ApiPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paste': {
      id: '/api/paste'
      path: '/api/paste'
      fullPath: '/api/paste'
      preLoaderRoute: typeof ApiPasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ip': {
      id: '/api/ip'
      path: '/api/ip'
      fullPath: '/api/ip'
      preLoaderRoute: typeof ApiIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dig': {
      id: '/api/dig'
      path: '/api/dig'
      fullPath: '/api/dig'
      preLoaderRoute: typeof ApiDigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/currency': {
      id: '/api/currency'
      path: '/api/currency'
      fullPath: '/api/currency'
      preLoaderRoute: typeof ApiCurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/convert': {
      id: '/api/convert'
      path: '/api/convert'
      fullPath: '/api/convert'
      preLoaderRoute: typeof ApiConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paste/$id': {
      id: '/api/paste/$id'
      path: '/$id'
      fullPath: '/api/paste/$id'
      preLoaderRoute: typeof ApiPasteIdRouteImport
      parentRoute: typeof ApiPasteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPasteRouteChildren {
  ApiPasteIdRoute: typeof ApiPasteIdRoute
}

const ApiPasteRouteChildren: ApiPasteRouteChildren = {
  ApiPasteIdRoute: ApiPasteIdRoute,
}

const ApiPasteRouteWithChildren = ApiPasteRoute._addFileChildren(
  ApiPasteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioRoute: AudioRoute,
  CurrencyRoute: CurrencyRoute,
  DigRoute: DigRoute,
  DownloadRoute: DownloadRoute,
  EncodeRoute: EncodeRoute,
  ImagesRoute: ImagesRoute,
  IpRoute: IpRoute,
  PdfRoute: PdfRoute,
  ScreenshotRoute: ScreenshotRoute,
  SpeedRoute: SpeedRoute,
  TokenizerRoute: TokenizerRoute,
  VideoRoute: VideoRoute,
  ApiConvertRoute: ApiConvertRoute,
  ApiCurrencyRoute: ApiCurrencyRoute,
  ApiDigRoute: ApiDigRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  ApiIpRoute: ApiIpRoute,
  ApiPasteRoute: ApiPasteRouteWithChildren,
  ApiPdfRoute: ApiPdfRoute,
  ApiScreenshotRoute: ApiScreenshotRoute,
  ApiSpeedRoute: ApiSpeedRoute,
  PasteIdRoute: PasteIdRoute,
  PasteIndexRoute: PasteIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
